# -*- coding: utf-8 -*-
"""Marcel V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRdafuDQnqvJcfMyAOX3vZnWSD46A3Zc
"""

CLASSIFIERS = {
    "猫": "只",
    "狗": "只",
    "书": "本",
    "人": "个",
    "学生": "个",
    "车": "辆",
    "衣服": "件",
    "桌子": "张",
    "椅子": "把"
}

NUMBERS = {"一","二","三","四","五","六","七","八","九","十","两"}

ADJECTIVES = {"大", "小", "新", "旧", "漂亮", "可爱"}

def check_liang_vs_er(sentence, errors):
    """
    Fixes cases like:
    二只猫 -> 两只猫
    二只可爱的猫 -> 两只可爱的猫
    二个位老师 -> 两位老师   (if 位 is in your classifier data later)
    """
    for noun, clf in CLASSIFIERS.items():
        wrong_patterns = [
            f"二{clf}{noun}",
            f"二{clf}的{noun}",
        ]

        # adjective structure: 二只可爱的猫 / 二只漂亮猫
        for adj in ADJECTIVES:
            wrong_patterns.append(f"二{clf}{adj}{noun}")
            wrong_patterns.append(f"二{clf}{adj}的{noun}")

        for wrong in wrong_patterns:
            while wrong in sentence:
                position = sentence.find(wrong)
                correct = "两" + wrong[1:]
                explanation = "Use 两 instead of 二 with classifiers"

                errors.append((position, wrong, correct, explanation, "liang_vs_er"))
                sentence = sentence.replace(wrong, correct, 1)
        return sentence, errors

def check_classifiers(words):
  for i in range(len(words)-1):
    if words[i] in NUMBERS:
      noun = words[i+1]
      if noun in CLASSIFIERS:
        classifier = CLASSIFIERS[noun]

        if i+1 < len(words) and words[i+1] != classifier:
         print(f"Possible error: {words[i]} {noun}")
         print(f"Suggested: {words[i]} {classifier} {noun}")

def check_classifiers_in_string(sentence):

  sentence = sentence.replace(" ", "")
  errors = []

  for number in NUMBERS:
    for noun in CLASSIFIERS:

      classifier = CLASSIFIERS[noun]

      wrong_pattern = number + noun
      correct_pattern = number + classifier + noun

      if correct_pattern in sentence:
        continue

      while wrong_pattern in sentence:
        position = sentence.find(wrong_pattern)
        explanation = f"Missing classifier: {noun} requires {classifier} after the number"
        errors.append((position, wrong_pattern, correct_pattern, explanation))
        sentence = sentence.replace(wrong_pattern, correct_pattern, 1)

      for adj in ADJECTIVES:
        wrong_pattern_2 = number + adj + noun
        correct_pattern_2 = number + classifier + adj + noun

        if correct_pattern_2 in sentence:
          continue

        while wrong_pattern_2 in sentence:
          position = sentence.find(wrong_pattern_2)
          explanation = f"Missing classifier: {noun} requires {classifier} after the number"
          errors.append((position, wrong_pattern_2, correct_pattern_2, explanation, "missing_classifier"))
          sentence = sentence.replace(wrong_pattern_2, correct_pattern_2, 1)

        wrong_pattern_4 = number + adj + "的" + noun
        correct_pattern_4 = number + classifier + adj + "的" + noun

        if correct_pattern_4 in sentence:
          continue

        while wrong_pattern_4 in sentence:
          position = sentence.find(wrong_pattern_4)
          explanation = f"Missing classifier: {noun} requires {classifier} after the number"
          errors.append((position, wrong_pattern_4, correct_pattern_4, explanation, "missing_classifier"))
          sentence = sentence.replace(wrong_pattern_4, correct_pattern_4, 1)

        for wrong_cl in CLASSIFIERS.values():
          correct_cl = CLASSIFIERS[noun]

          if wrong_cl != correct_cl:
            wrong_pattern_3 = number + wrong_cl + noun
            correct_pattern_3 = number + correct_cl + noun

            while wrong_pattern_3 in sentence:
              position = sentence.find(wrong_pattern_3)
              explanation = f"{wrong_cl} is not the correct classifier for {noun}; use {correct_cl} instead"
              errors.append((position, wrong_pattern_3, correct_pattern_3, explanation, "wrong_classifier"))
              sentence = sentence.replace(wrong_pattern_3, correct_pattern_3, 1)


  sentence, errors = check_liang_vs_er(sentence, errors)
  return errors, sentence

sentence = "二只猫"
words = sentence.split()

errors, corrected = check_classifiers_in_string(sentence)

print("Errors found:")
print("-" * 30)

print(f"Total errors: {len(errors)}\n")

errors.sort()
for position, wrong, correct, explanation, error_type in errors:
  print(f"[{position}] {wrong} -> {correct}")
  print(f"Type: {error_type}")
  print(f"Explanation: {explanation}")
  print()

print("\nCorrected sentence:")
print(corrected)